package steampipe

import (
	"github.com/opengovern/og-describer-github/pkg/sdk/es"
)

var Map = map[string]string{
  "Github/Actions/Artifact": "github_actions_artifact",
  "Github/Actions/Repository/Runner": "github_actions_repository_runner",
  "Github/Actions/Repository/Secret": "github_actions_repository_secret",
  "Github/Actions/Repository/Workflow_run": "github_actions_repository_workflow_run",
  "Github/Blob": "github_blob",
  "Github/Branch": "github_branch",
  "Github/Branch/Protection": "github_branch_protection",
  "Github/Commit": "github_commit",
  "Github/CommunityProfile": "github_community_profile",
  "Github/Gitignore": "github_gitignore",
  "Github/Issue/Comment": "github_issue_comment",
  "Github/License": "github_license",
  "Github/Organization/Collaborator": "github_organization_collaborators",
  "Github/Organization/DependabotAlert": "github_organization_dependabot_alert",
  "Github/Organization/ExternalIdentity": "github_organization_external_identity",
  "Github/Organization/Member": "github_organization_member",
  "Github/PullRequest": "github_pull_request",
  "Github/Repository/Collaborator": "github_repository_collaborator",
  "Github/Repository/DependabotAlert": "github_repository_dependabot_alert",
  "Github/Repository/Deployment": "github_repository_deployment",
  "Github/Repository/Environment": "github_repository_environment",
  "Github/Repository/Ruleset": "github_repository_ruleset",
  "Github/Repository/SBOM": "github_repository_sbom",
  "Github/Repository/VulnerabilityAlert": "github_repository_vulnerability_alert",
  "Github/Stargazer": "github_stargazer",
  "Github/Tag": "github_tag",
  "Github/Team/Member": "github_team_member",
  "Github/Team/Repository": "github_team_repository",
  "Github/Traffic/View/Daily": "github_traffic_view_daily",
  "Github/Traffic/View/Weekly": "github_traffic_view_weekly",
  "Github/Tree": "github_tree",
  "GithubUser": "github_user",
  "GithubWorkflow": "github_workflow",
}

var DescriptionMap = map[string]interface{}{
  "Github/Actions/Artifact": opengovernance.Artifact{},
  "Github/Actions/Repository/Runner": opengovernance.Runner{},
  "Github/Actions/Repository/Secret": opengovernance.Secret{},
  "Github/Actions/Repository/Workflow_run": opengovernance.WorkflowRun{},
  "Github/Blob": opengovernance.Blob{},
  "Github/Branch": opengovernance.Branch{},
  "Github/Branch/Protection": opengovernance.BranchProtection{},
  "Github/Commit": opengovernance.Commit{},
  "Github/CommunityProfile": opengovernance.CommunityProfile{},
  "Github/Gitignore": opengovernance.GitIgnore{},
  "Github/Issue/Comment": opengovernance.IssueComment{},
  "Github/License": opengovernance.License{},
  "Github/Organization/Collaborator": opengovernance.OrgCollaborators{},
  "Github/Organization/DependabotAlert": opengovernance.OrgAlertDependabot{},
  "Github/Organization/ExternalIdentity": opengovernance.OrgExternalIdentity{},
  "Github/Organization/Member": opengovernance.OrgMembers{},
  "Github/PullRequest": opengovernance.PullRequest{},
  "Github/Repository/Collaborator": opengovernance.RepoCollaborators{},
  "Github/Repository/DependabotAlert": opengovernance.RepoAlertDependabot{},
  "Github/Repository/Deployment": opengovernance.RepoDeployment{},
  "Github/Repository/Environment": opengovernance.RepoEnvironment{},
  "Github/Repository/Ruleset": opengovernance.RepoRuleSet{},
  "Github/Repository/SBOM": opengovernance.RepoSBOM{},
  "Github/Repository/VulnerabilityAlert": opengovernance.RepoVulnerabilityAlert{},
  "Github/Stargazer": opengovernance.Stargazer{},
  "Github/Tag": opengovernance.Tag{},
  "Github/Team/Member": opengovernance.TeamMembers{},
  "Github/Team/Repository": opengovernance.TeamRepository{},
  "Github/Traffic/View/Daily": opengovernance.TrafficViewDaily{},
  "Github/Traffic/View/Weekly": opengovernance.TrafficViewWeekly{},
  "Github/Tree": opengovernance.Tree{},
  "GithubUser": opengovernance.User{},
  "GithubWorkflow": opengovernance.Workflow{},
}

var ReverseMap = map[string]string{
  "github_actions_artifact": "Github/Actions/Artifact",
  "github_actions_repository_runner": "Github/Actions/Repository/Runner",
  "github_actions_repository_secret": "Github/Actions/Repository/Secret",
  "github_actions_repository_workflow_run": "Github/Actions/Repository/Workflow_run",
  "github_blob": "Github/Blob",
  "github_branch": "Github/Branch",
  "github_branch_protection": "Github/Branch/Protection",
  "github_commit": "Github/Commit",
  "github_community_profile": "Github/CommunityProfile",
  "github_gitignore": "Github/Gitignore",
  "github_issue_comment": "Github/Issue/Comment",
  "github_license": "Github/License",
  "github_organization_collaborators": "Github/Organization/Collaborator",
  "github_organization_dependabot_alert": "Github/Organization/DependabotAlert",
  "github_organization_external_identity": "Github/Organization/ExternalIdentity",
  "github_organization_member": "Github/Organization/Member",
  "github_pull_request": "Github/PullRequest",
  "github_repository_collaborator": "Github/Repository/Collaborator",
  "github_repository_dependabot_alert": "Github/Repository/DependabotAlert",
  "github_repository_deployment": "Github/Repository/Deployment",
  "github_repository_environment": "Github/Repository/Environment",
  "github_repository_ruleset": "Github/Repository/Ruleset",
  "github_repository_sbom": "Github/Repository/SBOM",
  "github_repository_vulnerability_alert": "Github/Repository/VulnerabilityAlert",
  "github_stargazer": "Github/Stargazer",
  "github_tag": "Github/Tag",
  "github_team_member": "Github/Team/Member",
  "github_team_repository": "Github/Team/Repository",
  "github_traffic_view_daily": "Github/Traffic/View/Daily",
  "github_traffic_view_weekly": "Github/Traffic/View/Weekly",
  "github_tree": "Github/Tree",
  "github_user": "GithubUser",
  "github_workflow": "GithubWorkflow",
}
